### ISSUE TITLE
conf for nginx

### ISSUE THREAD

**Issue by ttjaden** [Andreas-Bresch/vmailManage#8]
Hi! Thanks for your vmailManage-Tool. I followed the new Tutorial  from Thomas Leister to set up a Mail-Server and wanted to use your tool for managing the Accounts.

Can you update your Wiki for an nginx conf-file?

**Comment by Andreas-Bresch** [comment]
nginx does not support .htaccess.
Because of security the .htaccass is very important.
It forbids to browse the directories and open configuration files.
Besides it sets the directory-index to app.php and manages the rewrite-rules.

But it is possible to run it with nginx. Look here https://www.google.de/search?q=nginx+symfony

**Comment by ttjaden** [comment]
Thanks, with that information I got it running. A little problem remains:
When I log in, i can see the Domains / Accounts / Aliases which i set up over terminal with mysql. But when I try to make changes or e.g. add a new account, I get the following error:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
```
Do you know, how to investigate further? The error.log is empty and the access.log only

**Comment by Andreas-Bresch** [comment]
I forgot you, sorry.
Did you solve the problem?

**Comment by ttjaden** [comment]
Yes. I found out that the sql-user hat no permission to write or delete. After changing this, your vmailManage works. Thanks!

**Comment by Andreas-Bresch** [comment]
Great.
